In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../datasets/1429_1.csv")

df.head()

C:\Users\d_fon\AppData\Local\Temp\ipykernel_25548\1564300953.py:1: DtypeWarning: Columns (1: name, 10: reviews.didPurchase) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../datasets/1429_1.csv")

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username
0,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,This product so far has not disappointed. My c...,Kindle,NaN,NaN,Adapter
1,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,great for beginner or experienced person. Boug...,very fast,NaN,NaN,truman
2,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,NaN,NaN,DaveZ
3,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5620406/review...,I've had my Fire HD 8 two weeks now and I love...,Good!!!,NaN,NaN,Shacks
4,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,NaN,NaN,explore42

In [3]:
df.shape

(34660, 21)

In [4]:
df.columns

Index(['id', 'name', 'asins', 'brand', 'categories', 'keys', 'manufacturer',
       'reviews.date', 'reviews.dateAdded', 'reviews.dateSeen',
       'reviews.didPurchase', 'reviews.doRecommend', 'reviews.id',
       'reviews.numHelpful', 'reviews.rating', 'reviews.sourceURLs',
       'reviews.text', 'reviews.title', 'reviews.userCity',
       'reviews.userProvince', 'reviews.username'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 34660 entries, 0 to 34659
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    34660 non-null  str
 1   name                  27900 non-null  str
 2   asins                 34658 non-null  str
 3   brand                 34660 non-null  str
 4   categories            34660 non-null  str
 5   keys                  34660 non-null  str
 6   manufacturer          34660 non-null  str
 7   reviews.date          34621 non-null  str
 8   reviews.dateAdded     24039 non-null  str
 9   reviews.dateSeen      34660 non-null  str
 10  reviews.didPurchase   1 non-null      object
 11  reviews.doRecommend   34066 non-null  object
 12  reviews.id            1 non-null      float64
 13  reviews.numHelpful    34131 non-null  float64
 14  reviews.rating        34627 non-null  float64
 15  reviews.sourceURLs    34660 non-null  str
 16  reviews.text          34659 non-null  str
 17  reviews.title         34654 non-null  str
 18  reviews.userCity      0 non-null      float64
 19  reviews.userProvince  0 non-null      float64
 20  reviews.username      34653 non-null  str
dtypes: float64(5), object(2), str(14)
memory usage: 5.6+ MB

In [6]:
df.isna().sum()

id                          0
name                     6760
asins                       2
brand                       0
categories                  0
keys                        0
manufacturer                0
reviews.date               39
reviews.dateAdded       10621
reviews.dateSeen            0
reviews.didPurchase     34659
reviews.doRecommend       594
reviews.id              34659
reviews.numHelpful        529
reviews.rating             33
reviews.sourceURLs          0
reviews.text                1
reviews.title               6
reviews.userCity        34660
reviews.userProvince    34660
reviews.username            7
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df["reviews.rating"].value_counts().sort_index()

reviews.rating
1.0      410
2.0      402
3.0     1499
4.0     8541
5.0    23775
Name: count, dtype: int64

In [9]:
df["reviews.rating"].value_counts(normalize=True).sort_index() * 100

reviews.rating
1.0     1.184047
2.0     1.160944
3.0     4.328992
4.0    24.665723
5.0    68.660294
Name: proportion, dtype: float64

In [10]:
df["name"].nunique()

48

In [11]:
df["name"].value_counts().head(10)

name
Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes Special Offers, Magenta                                                                           10966
Echo (White),,,\r\nEcho (White),,,                                                                                                                3309
Amazon Kindle Paperwhite - eBook reader - 4 GB - 6 monochrome Paperwhite - touchscreen - Wi-Fi - black,,,                                         3176
All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi, 16 GB - Includes Special Offers, Magenta                                                           2814
Amazon Fire Tv,,,\r\nAmazon Fire Tv,,,                                                                                                            2527
Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16 GB, Green Kid-Proof Case                                                                           1685
Brand New Amazon Kindle Fire 16gb 7 Ips Display Tablet Wifi 16 Gb Blue,,,                                                                         1038
Kindle Voyage E-reader, 6 High-Resolution Display (300 ppi) with Adaptive Built-in Light, PagePress Sensors, Wi-Fi - Includes Special Offers,      580
Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes Special Offers, Black                                                                               372
Amazon - Amazon Tap Portable Bluetooth and Wi-Fi Speaker - Black,,,\r\nAmazon - Amazon Tap Portable Bluetooth and Wi-Fi Speaker - Black,,,         318
Name: count, dtype: int64

In [12]:
df[df["reviews.text"].duplicated(keep=False)][
    ["name", "reviews.rating", "reviews.text"]
].sort_values("reviews.text").head(20)

Empty DataFrame
Columns: [name, reviews.rating, reviews.text]
Index: []

In [13]:
df["review_length"] = df["reviews.text"].fillna("").str.split().str.len()

df["review_length"].describe()

count    34660.000000
mean        30.403289
std         34.641440
min          0.000000
25%         13.000000
50%         21.000000
75%         35.000000
max       1858.000000
Name: review_length, dtype: float64

In [14]:
df[["reviews.text", "review_length"]].sort_values(
    "review_length"
).head(10)

                                            reviews.text  review_length
3111                                                 NaN              0
3436                                                Best              1
34554  Great!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!#...              1
3446                                             Awesome              1
3230                                              thanks              1
9533   Loveeeeeeeee.....................................              1
15870  Great-----------------------------------------...              1
3471                                               Dandy              1
783    Thank............................................              1
6724                                              #NAME?              1

In [15]:
df[["reviews.text", "review_length"]].sort_values(
    "review_length",
    ascending=False
).head(10)

                                            reviews.text  review_length
21231  This is a review of the Kindle Paperwhite laun...           1858
2932   I've had lots of tablets in the past, mostly f...           1539
31770  Cord cutter here. We had been wanting to dump ...            750
2870   Even when I’m outside in bright sunlight, the ...            709
2857   Despite not being able to get one of these fro...            669
12021  I am amazed at this little tablet! I had, and ...            578
28940  As a bluetooth speaker, the Tap rocks! The sou...            503
9547   I was pleasantly surprised that I have enjoyed...            503
2896   I recently ordered my 8th Kindle. It was to re...            487
26316  I've been considering the whole "smart home" p...            487

In [16]:
df["categories"].nunique()

41

In [17]:
df["categories"].value_counts().head(10)

categories
Fire Tablets,Tablets,Computers & Tablets,All Tablets,Electronics, Tech Toys, Movies, Music,Electronics,iPad & Tablets,Android Tablets,Frys                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               10966
Stereos,Remote Controls,Amazon Echo,Audio Docks & Mini Speakers,Amazon Echo Accessories,Kitchen & Dining Features,Speaker Systems,Electronics,TVs Entertainment,Clearance,Smart Hubs & Wireless Routers,Featured Brands,Wireless Speakers,Smart Home & Connected Living,Home Security,Kindle Store,Home Automation,Home, Garage & Office,Home,Voice-Enabled Smart Assistants,Virtual Assistant Speakers,Portable Audio & Headphones,Electronics Features,Amazon Device Accessories,iPod, Audio Player Accessories,Home & Furniture Clearance,Consumer Electronics,Smart Home,Surveillance,Home Improvement,Smart Home & Home Automation Devices,Smart Hubs,Home Safety & Security,Voice Assistants,Alarms & Sensors,Amazon Devices,Audio,Holiday Shop     6619
Back To College,College Electronics,College Tvs & Home Theater,Electronics,Tvs & Home Theater,Streaming Devices,Featured Brands,Amazon Devices,Holiday Shop,Ways To Shop,TV & Home Theater,Streaming Media Players,All Streaming Media Players,TVs Entertainment,Video Games,Kindle Store,Electronics Features,Kids & Family,Fire TV                                                                                                                                                                                                                                                                                                                                                                                                                      5056
Walmart for Business,Office Electronics,Tablets,Office,Electronics,iPad & Tablets,Windows Tablets,All Windows Tablets,Computers & Tablets,E-Readers & Accessories,E-Readers,eBook Readers,Kindle E-readers,Computers/Tablets & Networking,Tablets & eBook Readers,Electronics Features,Books & Magazines,Book Accessories,eReaders,TVs & Electronics,Computers & Laptops,Tablets & eReaders                                                                                                                                                                                                                                                                                                                                                               3176
Electronics,iPad & Tablets,All Tablets,Fire Tablets,Tablets,Computers & Tablets                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           2814
Tablets,Fire Tablets,Computers & Tablets,All Tablets                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1699
Computers/Tablets & Networking,Tablets & eBook Readers,Computers & Tablets,Tablets,All Tablets                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1038
Featured Brands,Electronics,Amazon Devices,Home,Home Improvement,Home Safety & Security,Home Security,Alarms & Sensors,Smart Home & Home Automation Devices,Mobile,Mobile Speakers,Mobile Bluetooth Speakers,Smart Hubs & Wireless Routers,Smart Hubs,Home, Garage & Office,Smart Home,Voice Assistants,Smart Home & Connected Living,Amazon Tap,Portable Audio,MP3 Accessories,Speakers,Amazon Echo,Electronics Features,TVs & Electronics,Portable Audio & Electronics,MP3 Player Accessories,Home Theater & Audio,Kindle Store,Frys,Electronic Components,Home Automation,Electronics, Tech Toys, Movies, Music,Audio,Bluetooth Speakers                                                                                                                636
Walmart for Business,Office Electronics,Tablets,Electronics,iPad & Tablets,All Tablets,Computers & Tablets,E-Readers & Accessories,Kindle E-readers,Electronics Features,eBook Readers,See more Amazon Kindle Voyage (Wi-Fi),See more Amazon Kindle Voyage 4GB, Wi-Fi  3G (Unlocked...                                                                                                                                                                                                                                                                                                                                                                                                                                                                     580
Amazon Devices & Accessories,Amazon Device Accessories,Power Adapters & Cables,Kindle Store,Kindle E-Reader Accessories,Kindle Paperwhite Accessories                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      402
Name: count, dtype: int64

In [18]:
df_clean = df.copy()

In [19]:
columns_to_drop = [
    "reviews.didPurchase",
    "reviews.id",
    "reviews.userCity",
    "reviews.userProvince"
]

df_clean = df_clean.drop(columns=columns_to_drop)

In [21]:
df_clean = df_clean.dropna(
    subset=["reviews.text", "reviews.rating"]
)

In [22]:
df_clean["reviews.rating"].value_counts().sort_index()

reviews.rating
1.0      410
2.0      402
3.0     1499
4.0     8541
5.0    23774
Name: count, dtype: int64

In [23]:
def rating_to_sentiment(rating):
    if rating <= 2:
        return "negative"
    elif rating == 3:
        return "neutral"
    else:
        return "positive"

df_clean["sentiment"] = df_clean["reviews.rating"].apply(rating_to_sentiment)

In [24]:
df_clean["sentiment"].value_counts()

sentiment
positive    32315
neutral      1499
negative      812
Name: count, dtype: int64

In [25]:
df_clean["sentiment"].value_counts(normalize=True) * 100

sentiment
positive    93.325825
neutral      4.329117
negative     2.345059
Name: proportion, dtype: float64

In [27]:
df_clean["reviews.text"] = (
    df_clean["reviews.text"]
    .astype(str)
    .str.strip()
    .str.replace(r"\s+", " ", regex=True))

In [28]:
(df_clean["reviews.text"].str.len() == 0).sum()

np.int64(0)

In [29]:
df_clean["reviews.text"].duplicated().sum()

np.int64(11)

In [30]:
print("Shape:", df_clean.shape)

print("\nMissing values:")
print(
    df_clean[
        ["reviews.text", "reviews.rating", "sentiment"]
    ].isna().sum()
)

print("\nSentiment distribution:")
print(df_clean["sentiment"].value_counts())

print("\nDuplicated review texts:")
print(df_clean["reviews.text"].duplicated().sum())

Shape: (34626, 19)

Missing values:
reviews.text      0
reviews.rating    0
sentiment         0
dtype: int64

Sentiment distribution:
sentiment
positive    32315
neutral      1499
negative      812
Name: count, dtype: int64

Duplicated review texts:
11

In [31]:
duplicates = df_clean[
    df_clean["reviews.text"].duplicated(keep=False)
].sort_values("reviews.text")

duplicates[
    ["name", "reviews.rating", "sentiment", "reviews.text"]
]

,name,reviews.rating,sentiment,reviews.text
15438,Brand New Amazon Kindle Fire 16gb 7 Ips Displa...,2.0,negative,Amazon fire is a good tablet if you like e-boo...
15770,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",2.0,negative,Amazon fire is a good tablet if you like e-boo...
20427,"Kindle Voyage E-reader, 6 High-Resolution Disp...",4.0,positive,Bought this for my son to encourage his readin...
21274,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",4.0,positive,Bought this for my son to encourage his readin...
21869,"Echo (White),,,\r\nEcho (White),,,",5.0,positive,Easy to navigatePerfect for little ones Buy a ...
5750,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",5.0,positive,Easy to navigatePerfect for little ones Buy a ...
13323,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",5.0,positive,Great product and only $40! I purchased 2 of t...
21870,"Echo (White),,,\r\nEcho (White),,,",5.0,positive,Great product and only $40! I purchased 2 of t...
21293,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",5.0,positive,I needed a tablet to keep at the hospital duri...
2619,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",5.0,positive,I needed a tablet to keep at the hospital duri...
21588,"Echo (White),,,\r\nEcho (White),,,",5.0,positive,I used a couple of the brands that are just pr...
5357,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",5.0,positive,I used a couple of the brands that are just pr...
21275,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",4.0,positive,"If you like to read books, I totally recommend..."
19978,Amazon Kindle Paperwhite - eBook reader - 4 GB...,4.0,positive,"If you like to read books, I totally recommend..."
21549,"Echo (White),,,\r\nEcho (White),,,",4.0,positive,Needed an inexpensive and portable Alexa devic...
1693,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",4.0,positive,Needed an inexpensive and portable Alexa devic...
21272,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",4.0,positive,Purchased this as an upgrade to the first gene...
17667,Amazon Kindle Paperwhite - eBook reader - 4 GB...,4.0,positive,Purchased this as an upgrade to the first gene...
869,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",2.0,negative,This tablet could be so much better if the app...
21292,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",2.0,negative,This tablet could be so much better if the app...
28726,NaN,5.0,positive,This was an Xmas gift for my wife. She had wan...
28935,NaN,5.0,positive,This was an Xmas gift for my wife. She had wan...

In [32]:
df_clean = df_clean.drop_duplicates(
    subset=["reviews.text"],
    keep="first"
)

In [33]:
print("Shape:", df_clean.shape)
print("Duplicated texts:", df_clean["reviews.text"].duplicated().sum())

Shape: (34615, 19)
Duplicated texts: 0

In [34]:
print("Shape:", df_clean.shape)

print("\nMissing values:")
print(
    df_clean[
        ["reviews.text", "reviews.rating", "sentiment"]
    ].isna().sum()
)

print("\nSentiment distribution:")
print(df_clean["sentiment"].value_counts())

print("\nDuplicated review texts:")
print(df_clean["reviews.text"].duplicated().sum())

Shape: (34615, 19)

Missing values:
reviews.text      0
reviews.rating    0
sentiment         0
dtype: int64

Sentiment distribution:
sentiment
positive    32306
neutral      1499
negative      810
Name: count, dtype: int64

Duplicated review texts:
0